### ISSUE TITLE
ohh, man. Nice work.

### ISSUE THREAD

**Issue by xdearboy** [VoidAlastor/voidCord#1]
Good client, oxygen is very good client, but you is better.

**Comment by VoidAlastor** [comment]
Приятно, что хоть кто-то заметил мой клиент, тем более из наших(имею ввиду как язык так и некую пренадлежность к крашерам)
Жаль что до этого у нас с тобой диалог не очень сложился xd
![image](https://user-images.githubusercontent.com/119633789/213942259-99b0a350-f3aa-48be-aed4-f4567973f90f.png)

**Comment by xdearboy** [comment]
АХАХААВАЪХЗВАЪХАЗВ СОРРИ АВЪХЗАВХЪВАЗ

**Comment by xdearboy** [comment]
> Приятно, что хоть кто-то заметил мой клиент, тем более из наших(имею ввиду как язык так и некую пренадлежность к крашерам) Жаль что до этого у нас с тобой диалог не очень сложился xd ![image](https://user-images.githubusercontent.com/119633789/213942259-99b0a350-f3aa-48be-aed4-f4567973f90f.png)

аааа, у тебя имя на М начинается? Ну привет мой дорогой друг.

**Comment by xdearboy** [comment]
> Приятно, что хоть кто-то заметил мой клиент, тем более из наших(имею ввиду как язык так и некую пренадлежность к крашерам) Жаль что до этого у нас с тобой диалог не очень сложился xd ![image](https://user-images.githubusercontent.com/119633789/213942259-99b0a350-f3aa-48be-aed4-f4567973f90f.png)
![image](https://user-images.githubusercontent.com/105206420/216103547-63ca358d-49f9-46e9-86ae-76b1675ba02a.png)
